name: Vue Wechat Login
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
        with:
          ref: master
      - name: Lint
        run: |
          npm install
          npm run-script lint
